/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 expense.gltf --transform 
Files: expense.gltf [261.05KB] > C:\Users\AKASH\Desktop\expense\expense-transformed.glb [107.36KB] (59%)
Author: cozypoly3d (https://sketchfab.com/cozypoly3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free--money-currency-basic-pack-4368d88ee80f453dbbdbf78784bc32ad
Title: FREE _Money Currency_Basic Pack
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/expense-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cash_Material001_0.geometry} material={materials['Material.001']} position={[-9, 0, 9]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1, 2, 0.068]} />
    </group>
  )
}

useGLTF.preload('/expense-transformed.glb')
