/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hotel.gltf --transform 
Files: hotel.gltf [12.43MB] > C:\Users\AKASH\Desktop\3DHOTEL\hotel-transformed.glb [638.22KB] (95%)
Author: KattyLi (https://sketchfab.com/KattyLi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hotel-55c789602a4a4cabb93dd87207bd233f
Title: Hotel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hotel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube1_LP_0.geometry} material={materials.material} position={[0, 3.433, 5.916]} scale={[5.962, 6.796, 3.573]} />
      <mesh geometry={nodes.polySurface4_lamp_0.geometry} material={materials.lamp} position={[0.252, 0, 0]} />
      <mesh geometry={nodes.polySurface22_glass_0.geometry} material={materials.glass} />
    </group>
  )
}

useGLTF.preload('/hotel-transformed.glb')
