/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PassPort.gltf --transform 
Files: PassPort.gltf [4MB] > C:\Users\AKASH\Desktop\Documet\PassPort-transformed.glb [281.18KB] (93%)
Author: Verticle (https://sketchfab.com/verticle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-leather-passport-3a162dd69c31429fb162313c04f3954c
Title: Classic leather passport
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PassPort-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[0, -0.2, 0]} // Adjusts the position [x, y, z]
        rotation={[Math.PI / 2.5, Math.PI / 4, 0]} // Tilts the model to match the perspective
        scale={0.474}
      />
    </group>
  )
}

useGLTF.preload('/PassPort-transformed.glb')
